### ISSUE TITLE
Resource packs from plugins other than VanillaAdditions do not work correctly

### ISSUE THREAD

**Issue by DrkMatr1984** [chrismin13/AdditionsAPI#19]
I can confirm the plugin is not working for 1.13, but I'm not sure its for the reason @Eric_Minecraft says, as it does indeed work for VanillaAdditions and 1.13, but not for my own Custom Plugin I am developing.

**Comment by chrismin13** [comment]
Please provide some extra info regarding your setup. I have already made a separate issue for Eric's report, however, many are already using Vanilla Additions with 1.13 and are having no issues.
Issue closed, feel free to open it if you manage to recreate the situation or have any data that would help with tracking down the issue.
