### ISSUE TITLE
No durability penalty for inappropraite tool

### ISSUE THREAD

**Issue by ArZorMC** [chrismin13/AdditionsAPI#27]
In vanilla, if you use the wrong tool for the job there is a durability cost penalty. For example, if you use a pickaxe to break blocks designed to be broken with a shovel it will cost 2 durability rather than just 1. It seems reasonable this should apply to custom material items as well as the hammer

**Comment by chrismin13** [comment]
Are you sure about that? The testing done while creating the Additions API durability system was extensive and I never came across that behavior, even though I originally also though that was how it worked. As far as I can tell, this isn't the case for most items, with some exceptions, like the Shears which work on a per block basis. If this is true, it'll require a lot of changes, but I doubt this is true

**Comment by ArZorMC** [comment]
Wow I've believed wrong this whole time. While there are a few cases where extra durability is used, it's not in the way i thought it was. I haven't dived into the code myself but according to the wiki here:
https://minecraft.gamepedia.com/Item_durability#Tool_durability
Yup i was totally mistaken.

**Comment by chrismin13** [comment]
Don't trust the wiki, it's been incorrect quite a few times! Experimenting in game with the version you want to use is always the best. Unfortunately, finding info online for things like these is very hard and isn't well documented sometimes.
Still, glad I can mark this issue as closed!
