### ISSUE TITLE
ClassNotFoundException (CustomItem)

### ISSUE THREAD

**Issue by FebScap** [chrismin13/AdditionsAPI#44]
Hey, I'm using you're API with my plugin in 1.15 Spigot. But the plugin crash when the serveur start. I got this error... Could you help me ?

> at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.jar:git-Paper-8]
>        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.jar:git-Paper-8]
>        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.jar:git-Paper-8]
>        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.jar:git-Paper-8]
>        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
> 
> Caused by: java.lang.ClassNotFoundException: com.chrismin13.additionsapi.items.CustomItem
>        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
>        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.jar:git-Paper-8]
>        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.jar:git-Paper-8]
>        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
>        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
>        ... 10 more
>

**Comment by FebScap** [comment]
Okay, after a lot of try. This error is solved. But now, I got another, and I can't find how to resolve it :/

Here is the report :

> [18:14:05 WARN]: [AdditionsAPI] Task #30 for AdditionsAPI v1.3.2 generated an exception
> java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
> at us.fihgu.toolbox.file.FileUtils.deleteFolder(FileUtils.java:60) ~[?:?]
> at us.fihgu.toolbox.resourcepack.ResourcePackManager.buildResourcePack(ResourcePackManager.java:113) ~[?:?]
> at com.chrismin13.additionsapi.AdditionsAPI.setupHTTPServer(AdditionsAPI.java:189) ~[?:?]
> at com.chrismin13.additionsapi.AdditionsAPI.load(AdditionsAPI.java:214) ~[?:?]
> at com.chrismin13.additionsapi.AdditionsAPI.lambda$onEnable$0(AdditionsAPI.java:176) ~[?:?]
> at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.jar:git-Paper-8]
> at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.jar:git-Paper-8]
> at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.jar:git-Paper-8]
> at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.jar:git-Paper-8]
> at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.jar:git-Paper-8]
> at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.jar:git-Paper-8]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.jar:git-Paper-8]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.jar:git-Paper-8]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
> ... 12 more

​Thanks all for help :)

**Comment by DrkMatr1984** [comment]
Fixed with [commit cbb1c98b2ac24630cda7104ae49f0ea2e9f4fbce](https://github.com/chrismin13/AdditionsAPI/commit/cbb1c98b2ac24630cda7104ae49f0ea2e9f4fbce)
