### ISSUE TITLE
Add getItemMeta / setItemMeta and possibility add NBTCompound etc...

### ISSUE THREAD

**Issue by Euphillya** [chrismin13/AdditionsAPI#50]
Hello on your API, its possible add modify NBT tag for custom your item ?

**Comment by chrismin13** [comment]
Take a look at the CustomItemStack object. You can create a new CustomItemStack by giving it a normal ItemStack that is a Custom Item.

https://chrismin13.github.io/AdditionsAPI/com/chrismin13/additionsapi/items/CustomItemStack.html#addAllNBTData-java.util.Map-

**Comment by Euphillya** [comment]
Ah yes sorry :/
